---
- name: Install / upgrade k3s on master node
  shell:
    cmd: |
      set -o pipefail
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC='server {{ extra_server_args | default("") }}' sh -
  args:
    executable: /bin/bash
  changed_when: False

- name: Read node-token from master
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token

- name: Store Master node-token
  set_fact:
    k3s_node_token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"